---
name: Setup Conventional Versioning Binary
author: "Jontze"
description: "Setup Conventional Versioning Binary"
inputs:
  version:
    description: "Version of Conventional Versioning to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Conventional Versioning Binary
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: jontze/conventional-versioning
        tag: ${{ inputs.version }}
        cache: enable
