name: CI
on:
  push:
    branches:
      - main

jobs:
  update_changelog:
    permissions:
      contents: write
    uses: "./.github/workflows/changelog_gen.yaml"
    with:
      changelog_file: "CHANGELOG.md"
      cliff_config: "cliff.toml"
    secrets: inherit
