---
name: Rust Test
on:
  workflow_call:
    inputs:
      build:
        default: false
        type: boolean
        required: false
        description: Test with build
      unit-tests:
        default: false
        type: boolean
        required: false
        description: Run with unit tests
      unit-test-workspace:
        description: Run all tests in the workspace
        default: false
        required: false
        type: boolean
      working-directory:
        description: Working directory
        default: .
        required: false
        type: string
      toolchain:
        description: Rust toolchain to use
        default: stable
        required: false
        type: string

jobs:
  lint:
    name: Lint
    uses: jontze/.workflows/.github/workflows/rust_lint.yaml@main
    with:
      toolchain: ${{ inputs.toolchain }}
      working-directory: ${{ inputs.working-directory }}

  clippy:
    name: Clippy
    uses: jontze/.workflows/.github/workflows/rust_clippy.yaml@main
    with:
      toolchain: ${{ inputs.toolchain }}
      working-directory: ${{ inputs.working-directory }}

  build:
    name: Build
    if: inputs.build
    uses: jontze/.workflows/.github/workflows/rust_build.yaml@main
    with:
      toolchain: ${{ inputs.toolchain }}
      working-directory: ${{ inputs.working-directory }}
      is-release: false

  unit-test:
    name: Unit Test
    if: inputs.unit-tests
    uses: jontze/.workflows/.github/workflows/rust_unit_test.yaml@main
    with:
      toolchain: ${{ inputs.toolchain }}
      working-directory: ${{ inputs.working-directory }}
      workspace: ${{ inputs.unit-test-workspace }}
